project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Social data analysis and visualization project" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



